apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-helloworld-env
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/gswk/knative-helloworld-env:latest
            env:
            - name: FROM
              value: "env sample"